# WARNING: This file is automatically generated. Do not edit directly.
# Instead, modify the flake.nix.tpl file and run the update script.

{
  description = "KCL toolchain flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        getArch = system:
          if system == "x86_64-linux" then "linux-amd64"
          else if system == "aarch64-linux" then "linux-arm64"
          else if system == "x86_64-darwin" then "darwin-amd64"
          else if system == "aarch64-darwin" then "darwin-arm64"
          else throw "Unsupported system: ${system}";

        cli = pkgs.stdenv.mkDerivation rec {
          pname = "kcl-cli";
          version = "0.11.0-alpha.1";

          src = pkgs.fetchurl {
            url = "https://github.com/kcl-lang/cli/releases/download/v${version}/kcl-v${version}-${getArch system}.tar.gz";
            sha256 = {
              x86_64-linux = "0542dl7h705sqddy4fmv2865r2mmnkmxwpw48173bjjwq1cramiy";
              aarch64-linux = "0a3vyfqa588yysqhpa75zgkxa5c11r0wxds5m107f7b4p143s0wn";
              x86_64-darwin = "10j04sjivx6b4b219wdy0qcnn1vv4r7xppw9jmyyikhfv04n5rvs";
              aarch64-darwin = "0cvridgvqvr7dldwfyfjk2q0psjwb4d4r2qfnajzinmhiq4snk9v";
            }.${system};
          };

          dontUnpack = true;

          installPhase = ''
            mkdir -p $out/bin
            tar -xzf $src -C $out/bin
            # Ensure the file is named 'kcl'
            if [ ! -f $out/bin/kcl ]; then
              mv $out/bin/kcl-cli $out/bin/kcl || true
            fi
            chmod +x $out/bin/kcl
          '';
        };

        language-server = pkgs.stdenv.mkDerivation rec {
          pname = "kcl-language-server";
          version = "0.11.0";

          src = pkgs.fetchurl {
            url = "https://github.com/kcl-lang/kcl/releases/download/v${version}/kclvm-v${version}-${getArch system}.tar.gz";
            sha256 = {
              x86_64-linux = "1j1xbjjl30x1aq6na7gck4kdzscgqb17wza4k241l8k5swlgg0lm";
              aarch64-linux = "0vcw3hr15yvsbsc0j2kfss8nxzd78c9hdpfljqav7d2vkkhdjnp9";
              x86_64-darwin = "0vfcj2030873rw7lala22q85rydalj750nx6jlbri8rm5czmh7zr";
              aarch64-darwin = "0m8bgqas8f0aywhrbwmlfznmhij088jhnj0h5d2pk8wp5ay5hj4c";
            }.${system};
          };

          installPhase = ''
            mkdir -p $out/bin
            cp bin/kcl-language-server $out/bin/
          '';
        };

        getArchKubectlKcl = system:
          if system == "x86_64-linux" then "linux-amd64"
          else if system == "aarch64-linux" then "linux-arm64"
          else if system == "x86_64-darwin" then "macos-amd64"
          else if system == "aarch64-darwin" then "macos-arm64"
          else throw "Unsupported system: ${system}";

        kubectl-kcl = pkgs.stdenv.mkDerivation rec {
          pname = "kubectl-kcl";
          version = "0.9.0";

          src = pkgs.fetchurl {
            url = "https://github.com/kcl-lang/kubectl-kcl/releases/download/v${version}/kubectl-kcl-${getArchKubectlKcl system}.tgz";
            sha256 = {
              x86_64-linux = "1242dvx9ph52yxq988n0fvsbm9wpchi4pwpwj2zbscw1hgy0apq8";
              aarch64-linux = "1d0yby7niw7npp5v5f91q20g2z4flnzkp6ydhc0sjwls3lwrj8g9";
              x86_64-darwin = "1qyrmfwabz0aa3bavjrijmq21gk1marks6b1k2vg1vy68z68pll7";
              aarch64-darwin = "1vz529yi5dz0wi0ymbg3q52ixqdfzv9czk8iwp94q5ffjqcvdf9j";
            }.${system};
          };

          installPhase = ''
            mkdir -p $out/bin
            cp bin/kubectl-kcl $out/bin/
          '';
        };

      in
      {
        default = {
          inherit cli language-server kubectl-kcl;
        };
      }
    );
}
